---
application: dev-tool
version: "2.0"

setup:
  go: 1.21

commands:
  build:
    summary: Build the mysql-exporter binary and Docker container
    command: |
      go build
      docker build -t mysql-exporter -f docker/Dockerfile .

  clean:
    summary: Clean all development binaries and folders
    command: |
      go clean

  test:
    summary: Run all tests
    command: |
      dev build
      docker-compose up -d mysql redis
      docker-compose run mysql-exporter -e INTEGRATION_TEST=true

  reset:
    summary: Run reset from dev.yml
    command: |
      docker-compose down
      go clean
